package au.superdraftfantasy.api.player;

public enum AflTeamEnum {
    ADELAIDE_CROWS,
    BRISBANE_LIONS,
    CARLTON_BLUES,
    COLLINGWOOD_MAGPIES,
    ESSENDON_BOMBERS,
    FREMANTLE_DOCKERS,
    GEELONG_CATS,
    GOLD_COAST_SUNS,
    GWS_GIANTS,
    HAWTHORN_HAWKS,
    MELBOURNE_DEMONS,
    NORTH_MELBOURNE_KANGAROOS,
    PORT_ADELAIDE_POWER,
    RICHMOND_TIGERS,
    ST_KILDA_SAINTS,
    SYDNEY_SWANS,
    WEST_COAST_EAGLES,
    WESTERN_BULLDOGS,
}