app.message: This is the property file for the ${spring.application.name} specific to PROD Environment.

spring:
  flyway:
    locations: classpath:/db/migration,classpath:/db/afterMigrate
  jpa:
    database: POSTGRESQL
    show-sql: false
    ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # Used to avoid boot up exception. See https://stackoverflow.com/questions/49110818/method-org-postgresql-jdbc-pgconnection-createclob-is-not-yet-implemented
        show_sql: false

  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    driverClassName: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
      hibernate:
        SQL: INFO
#        type: TRACE
